# Generated by Django 4.2.4 on 2023-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_name',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='frontend/public/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
