# Generated by Django 4.2.5 on 2023-10-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='details',
            field=models.TextField(default=True),
        ),
    ]
