# Generated by Django 4.2.5 on 2023-10-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
