name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test

    - name: Deploy to Apache Server
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server-ip "cd /path/to/your/project && git pull && pip install -r requirements.txt && python manage.py migrate && systemctl restart apache2"
      env:
        DJANGO_SETTINGS_MODULE: your_project.settings.production
